FROM quay.io/fedora/fedora-coreos:testing

RUN rpm-ostree install \
    htop \
    neovim \ 
    net-tools \
    openssh \
    openssl \
    ripgrep \
    symlinks \ 
    unzip \
    zip 

RUN ostree container commit && \
    mkdir -p /var/tmp && chmod -R 1777 /var/tmp
